# Generated by Django 2.2.10 on 2020-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200624_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': ' Food Item', 'verbose_name_plural': ' Food Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': ' Ordered Detail', 'verbose_name_plural': ' Ordered Details'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': ' Ordered Item', 'verbose_name_plural': ' Ordered Items'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': ' Customer', 'verbose_name_plural': ' Customers'},
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Sold Out')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Starters'), ('BF', 'Breakfast'), ('M', 'MainCourse'), ('SO', 'Soups'), ('B', 'Beverage')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('primary', "Chef's Special"), ('secondary', 'Best Seller'), ('danger', 'Must Try')], max_length=12),
        ),
    ]
